Controllers/DeprtmentController.cs
using AutoMapper;
using BLL2.Interfaces;
using BLL2.Repositories;
using DAL2;
using DAL2.Entities;
using EmployeesDashboard.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EmployeesDashboard.Controllers
{
    public class DeprtmentController : Controller
    {
       
        private readonly IUnitOfWork<Department2> _unitOfWork;
        private readonly IMapper _mapper;


        public DeprtmentController(IUnitOfWork<Department2> unitOfWork ,
            IMapper mapper )
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
           
        }
        public async Task<IActionResult> Index(string value)
        {
            if (string.IsNullOrEmpty(value))
            {
                var departments = await _unitOfWork.GenericRepository.GetAll();
                return View(_mapper.Map<IEnumerable<Department2>, IEnumerable<DepartmentViewModel>>(departments));
            }
            return View(_mapper.Map<IEnumerable<Department2>, IEnumerable<DepartmentViewModel>>( await _unitOfWork.DepartmentRepository.Search(value)));
        }

        [HttpGet]
        public async Task<IActionResult> Details(int? id , string ViewName = "Details")
        {
            if (id == null)
                return NotFound();
            var department = await _unitOfWork.GenericRepository.Get(id);
            if (department == null)
                return NotFound();
           
           return View( _mapper.Map<Department2 , DepartmentViewModel>(department));
        }


        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {

            return await Details(id, "Edit");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] string id , DepartmentViewModel department )
        {
            if (id != department.Id)
                return BadRequest();
            if(ModelState.IsValid)
            {
                await _unitOfWork.GenericRepository.Update( _mapper.Map<DepartmentViewModel , Department2>(department));
                return RedirectToAction(nameof(Index));
            }
            return View(department);
        }

        [HttpGet]
        public  IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(DepartmentViewModel department)
        {
            if (ModelState.IsValid)
            {
                await _unitOfWork.GenericRepository.Add(_mapper.Map<DepartmentViewModel, Department2>(department));
                return RedirectToAction("Index");
            }
                
            return View(department);
        }

        [HttpGet]
        public async Task<IActionResult> Delete (int?id)
        {
            return await Details(id , "Delete");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete([FromRoute] string id, DepartmentViewModel department)
        {
            if (id != department.Id)
                return BadRequest();
            await _unitOfWork.GenericRepository.Delete(_mapper.Map<DepartmentViewModel, Department2>(department));
            return RedirectToAction("Index");
        }

    }
}

Controllers/EmployeeController.cs
using AutoMapper;
using BLL2.Interfaces;
using DAL2.Entities;
using EmployeesDashboard.Helpers;
using EmployeesDashboard.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.IO;
using Microsoft.AspNetCore.Authorization;

namespace EmployeesDashboard.Controllers
{

    [Authorize]
    public class EmployeeController : Controller
    {
        private readonly IUnitOfWork<Employee> _unitOfWork;
        private readonly IMapper _mapper;


        public EmployeeController(IUnitOfWork<Employee> unitOfWork,
            IMapper mapper)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;

        }

        public async Task<IActionResult> Index(string value)
        {
            if (string.IsNullOrEmpty(value))
            {
                var employee = await _unitOfWork.GenericRepository.GetAll();
                var employeeViewModel =
               _mapper.Map<IEnumerable<Employee>, IEnumerable<EmployeeViewModel>>(employee);

                return View(employeeViewModel);
            }
            return View(_mapper.Map<IEnumerable<Employee>, IEnumerable<EmployeeViewModel>>(await _unitOfWork.EmployeeRepository.SearchByName(value)));

        }

        [HttpGet]
        public async Task< IActionResult >Details(int? id, string ViewName = "Details")
        {
            if (id == null)
                return NotFound();
            var employee =await _unitOfWork.GenericRepository.Get(id);
            if (employee == null)
                return NotFound();

            return View(_mapper.Map<Employee , EmployeeViewModel>(employee));
        }


        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {

            return await Details(id, "Edit");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult>Edit([FromRoute] string id, EmployeeViewModel employee)
        {
            if (id != employee.Id)
                return BadRequest();
            if (ModelState.IsValid)
            {
                
                var emp = _mapper.Map<EmployeeViewModel, Employee>(employee);
                emp.ImageName = DocumentSettings.SettingUploadFiles(employee.Image, "Images");
                await _unitOfWork.GenericRepository.Update(emp);
                return RedirectToAction(nameof(Index));
            }
            return View(employee);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task< IActionResult>Create( EmployeeViewModel employee)
        {
            if (ModelState.IsValid)
            {
                employee.ImageName = DocumentSettings.SettingUploadFiles(employee.Image, "Images");
                var emp = _mapper.Map<EmployeeViewModel, Employee>(employee);
               await _unitOfWork.GenericRepository.Add(emp);
                return RedirectToAction("Index");
            }

            return View(employee);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            return await Details(id, "Delete");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete([FromRoute] string id, EmployeeViewModel employee)
        {
            if (id != employee.Id)
                return BadRequest();
            var emp = _mapper.Map<EmployeeViewModel, Employee>(employee);
            DocumentSettings.DeleteFile( emp.ImageName, "images");
            await _unitOfWork.GenericRepository.Delete(emp);
           
            return RedirectToAction("Index");
        }
    }
}

Views/Shared/SearchPartialView.cshtml
<form asp-action="Index">
    <div class="container my-3">
        <div class="row">
            <div class="col-7">
                <input name="value" placeholder="Search by name"class="form-control w-100" />
            </div>
            <div class="col-3">

                <input type="submit" value="Search" class="btn btn-success w-100" />
            </div>
        </div>
    </div>

</form>

Views/Shared/_ButtonPartialView.cshtml
@model string

<a asp-action="Details" asp-route-id="@Model" class="btn btn-warning">Details</a>|
<a asp-action="Edit" asp-route-id="@Model" class="btn btn-primary">Edit</a>|
<a asp-action="Delete" asp-route-id="@Model" class="btn btn-danger">Delete</a>|

Views/Shared/_DetailsDeleteDepartPartialView.cshtml
@model EmployeesDashboard.Models.DepartmentViewModel


<div class="form-group">
    <label asp-for="@Model.Code" class="col-form-label"></label>
    <input asp-for="@Model.Code" class="form-control" readonly />
</div>
<div class="form-group">
    <label asp-for="@Model.Name" class="col-form-label"></label>
    <input asp-for="@Model.Name" class="form-control" readonly />
</div>

Views/Shared/_DetailsDeleteEmployeePartialView.cshtml
@model EmployeeViewModel


<dl class="row">
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Name)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Name)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Age)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Age)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Address)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Address)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Salary)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Salary)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.isActive)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.isActive)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Email)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Email)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.PhoneNumer)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.PhoneNumer)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.DateHire)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.DateHire)
    </dd>

    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Id)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Id)
    </dd>
    <dt class="col-sm-2">
       PIC
    </dt>
    <dd class="col-sm-10">
        <img src="~/Files/Images/@Model.ImageName" class="img-fluid img-thumbnail w-50" /> 
    </dd>
</dl>
<input type="hidden" asp-for="@Model.ImageName" />

Views/Shared/_EditCreateDepartmentPartialView.cshtml
@model EmployeesDashboard.Models.DepartmentViewModel


<div asp-validation-summary="ModelOnly" class="text-danger"></div>

<div class="form-group">
    <label asp-for="Code" class="control-label"></label>
    <input asp-for="Code" class="form-control" />
    <span asp-validation-for="Code" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Name" class="control-label"></label>
    <input asp-for="Name" class="form-control" />
    <span asp-validation-for="Name" class="text-danger"></span>
</div>

Views/Shared/_EditCreateEmployeePartialView.cshtml
@model EmployeeViewModel

<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<div class="form-group">
    <label asp-for="Name" class="control-label"></label>
    <input asp-for="Name" class="form-control" />
    <span asp-validation-for="Name" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Age" class="control-label"></label>
    <input asp-for="Age" class="form-control" />
    <span asp-validation-for="Age" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Address" class="control-label"></label>
    <input asp-for="Address" class="form-control" />
    <span asp-validation-for="Address" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Salary" class="control-label"></label>
    <input asp-for="Salary" class="form-control" />
    <span asp-validation-for="Salary" class="text-danger"></span>
</div>
<div class="form-group form-check">
    <label class="form-check-label">
        <input class="form-check-input" asp-for="isActive" /> @Html.DisplayNameFor(model => model.isActive)
    </label>
</div>
<div class="form-group">
    <label asp-for="Email" class="control-label"></label>
    <input asp-for="Email" class="form-control" />
    <span asp-validation-for="Email" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="PhoneNumer" class="control-label"></label>
    <input asp-for="PhoneNumer" class="form-control" />
    <span asp-validation-for="PhoneNumer" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="DateHire" class="control-label"></label>
    <input asp-for="DateHire" class="form-control" />
    <span asp-validation-for="DateHire" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Image" class="control-label"></label>
    <input type="file" asp-for="Image" class="form-control" />
    <span asp-validation-for="Image" class="text-danger"></span>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EmployeesDashboard</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EmployeesDashboard</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Deprtment" asp-action="Index">Departments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Registration">Register</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - EmployeesDashboard - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @await RenderSectionAsync("ScriptSection" , required: false)
</body>
</html>